---
- name: Deploy and start Apache HTTPD service
  hosts: all
  vars:
    web_server: httpd
    web_content: Test Web Page using Ansible Vars
  tasks:
    - name: Required packages are installed and up to date
      yum:
        name:
          - "{{ web_server  }}"
        state: present

    - name: The {{ web_server }} service is started and enabled
      service:
        name: "{{ web_server }}"
        enabled: true
        state: started

    - name: Web content is in place
      copy:
        content: "{{ web_content }}"
        dest: /var/www/html/index.html
